### ISSUE TITLE
可以推出arm版的吗

### ISSUE THREAD

**Issue by TingChieh** [shadowsocksrr/electron-ssr#11]

**Comment by Akkariiin** [comment]
arm能跑得起吗？

**Comment by jamesyangget** [comment]
> arm能跑得起吗？

树莓派4 应该可以跑的动了|･ω･｀)

**Comment by GeorgeCyr** [comment]
同求ARM版本，请求增加arm版本，谢谢。

**Comment by GeorgeCyr** [comment]
我能找到shadowsocks-qt的arm版本，但是目前还没有找到shadowsockR的arm 版本

**Comment by xVanTuring** [comment]
目前不会做arm版的 感觉性能捉急，但是我目前有个初始项目 [ssr_cli ](https://github.com/xVanTuring/ssr_cli) 提供web 控制界面 基于nodejs，不过要等一段时间（最近要准备考试）

**Comment by GeorgeCyr** [comment]
您好，请问这个web项目的开发需要多长时间，感觉这个web项目就会让SSR完全跨平台了。

**Comment by xVanTuring** [comment]
SSR本来就是跨平台的，只不过是没有 GUI的，这个项目至少到8月我才能继续写，估计八月中旬左右能有个可用版本

**Comment by GeorgeCyr** [comment]
请问您有关于如何在arm64-Linux上使用SSR的教程吗，我使用的机场都是ssr的，但是我找了很久都没找到arm平台上使用SSR的方法。

**Comment by xVanTuring** [comment]
[SSR-python](https://github.com/shadowsocksrr/shadowsocksr/tree/akkariiin/master) 是基于 python 的 只要你的设备上安装了 python 你就可以运行 shadowsocks/local.py （客户端） 来获取使用方式

**Comment by GeorgeCyr** [comment]
好的，感谢，可以用，只是没有客户端，配置起来可能麻烦一些，主要是不能使用链接订阅。
