### ISSUE TITLE
楼主能在协议和混淆加一个none吗？

### ISSUE THREAD

**Issue by Ericliu68** [shadowsocksrr/electron-ssr#18]
## Your os

ubuntu18.04
## The version of electron-ssr

0.2.4
## What's the problem

搭建了v2ray的服务器，配置了shadowsocks能使用，然后用windows的shadowsocks工具可以正常使用，但是ssr却不行！初步怀疑是协议和混淆的原因，请问能帮忙加上这些条件吗？

**Comment by Akkariiin** [comment]
底层调用的是py版本，要做测试的话可以手动调起来测试
