### ISSUE TITLE
kde下启动会打开 notify-osd 导致系统通知变成 gnome 风格

### ISSUE THREAD

**Issue by xgdgsc** [shadowsocksrr/electron-ssr#22]
## Your os
Ubuntu 16.04 kde

## The version of electron-ssr
 0.2.7 
## What's the problem
 kde下启动会打开 notify-osd 导致系统通知变成 gnome 风格

**Comment by xgdgsc** [comment]
删除了 notify-osd 后就不显示更新订阅的通知了，怀疑electron 版本太老

**Comment by Akkariiin** [comment]
现在electron更新了，你可以再试试看，看看还有没有问题

**Comment by xgdgsc** [comment]
谢谢， :airplane:  迁移到v2ray了
