### ISSUE TITLE
在xfce桌面会时不时的弹出Error Dialog

### ISSUE THREAD

**Issue by xkeyC** [shadowsocksrr/electron-ssr#26]
## 0.2.7
在xfce桌面会时不时的弹出以下错误（gnome，kde，实测没有问题），并阻塞代理进程（网页一直load，直到Time out），点击OK后恢复正常。在下载大文件或打开复杂网页时出现，有时会弹出十几个...
![image](https://user-images.githubusercontent.com/39891083/69003894-a5a98d80-0944-11ea-95d9-81d05e549a4f.png)

**Comment by AllenLucas** [comment]
同样遇到该问题。不知道如何解决，求助

**Comment by xVanTuring** [comment]
请问使用的是什么格式的包，appimage/pacman/tar.gz?

**Comment by xkeyC** [comment]
> 请问使用的是什么格式的包，appimage/pacman/tar.gz?

archlinuxcn源的包

**Comment by xVanTuring** [comment]
请问你使用的是什么浏览器，是否使用switchyomega插件？系统代理模式设定的是什么？

**Comment by xkeyC** [comment]
> 请问你使用的是什么浏览器，是否使用switchyomega插件？系统代理模式设定的是什么？

直接在终端export http_proxy

**Comment by xVanTuring** [comment]
我同样在使用终端设置并启动浏览器后并未出现你所说的情况，可否提供`~/.config/electron-ssr/logs/`路径下的log文件（注意删除敏感信息）

**Comment by xkeyC** [comment]
> 我同样在使用终端设置并启动浏览器后并未出现你所说的情况，可否提供`~/.config/electron-ssr/logs/`路径下的log文件（注意删除敏感信息）

暂时不便使用电脑，您可以尝试打开一个有频繁请求的网页，或下载大文件。

**Comment by xVanTuring** [comment]
在使用firefox观看youtube和下载ubuntu镜像时均无错误出现。

目前只能等你提供log文件后再继续分析。

**Comment by xVanTuring** [comment]
在firefox下测试并无错误出现，在chromium下出现了类似错误，你使用的也是chromium浏览器吗

**Comment by xkeyC** [comment]
> 在firefox下测试并无错误出现，在chromium下出现了类似错误，你使用的也是chromium浏览器吗

是的，google chrome。

**Comment by xVanTuring** [comment]
根据查看archlinuxcn对electron-ssr的打包发现其使用了`electron4`作为启动`electron`，而该版本开发时使用的是`1.8.2`版本，目前猜测可能是这个原因导致的各种问题。

**Comment by xVanTuring** [comment]
通过测试在GitHub release中的tar.gz版本，使用chome浏览器并未出现之前的错误。你可以测试一次如果仍然出现错误，则可能与electron的版本有关。测试时在xfce桌面下确保安装了`gconf`包。

**Comment by xVanTuring** [comment]
通过对比测试，使用archlinuxcn的ssr观看bilibili会出现大量的错误，而使用GitHub release 下的包则未出现任何问题，目前解决方案是使用release页面的包，或者等待下个版本发布，或者自行编译项目

**Comment by xkeyC** [comment]
> 通过对比测试，使用archlinuxcn的ssr观看bilibili会出现大量的错误，而使用GitHub release 下的包则未出现任何问题，目前解决方案是使用release页面的包，或者等待下个版本发布，或者自行编译项目

非常感谢！
