### ISSUE TITLE
是否可以添加aes-256-gcm加密方式

### ISSUE THREAD

**Issue by HydroCarbon** [shadowsocksrr/electron-ssr#27]
使用的是Manjaro Linux发行版，服务器端只能用 aes-256-gcm 加密，但是软件中并没有提供相应的加密方式，请问是否可以添加该加密方式？

**Comment by updater1234** [comment]
将后端改为shadowsocks-libev，然后在下图界面添加
![2019-11-23 00-24-12屏幕截图](https://user-images.githubusercontent.com/31512600/69442465-9cc31c80-0d87-11ea-9af2-ea8bf463a63f.png)

**Comment by HydroCarbon** [comment]
> 将后端改为shadowsocks-libev，然后在下图界面添加
> ![2019-11-23 00-24-12屏幕截图](https://user-images.githubusercontent.com/31512600/69442465-9cc31c80-0d87-11ea-9af2-ea8bf463a63f.png)

请问如何更改后端为Shadowsocks-libev，我尝试下载了文件，但是更改会报告错误

**Comment by HydroCarbon** [comment]
> 加

请问如何修改后端。。。

**Comment by HydroCarbon** [comment]
> 将后端改为shadowsocks-libev，然后在下图界面添加
> ![2019-11-23 00-24-12屏幕截图](https://user-images.githubusercontent.com/31512600/69442465-9cc31c80-0d87-11ea-9af2-ea8bf463a63f.png)

请问如何修改后端

**Comment by updater1234** [comment]
自己慢慢领悟吧
