### ISSUE TITLE
manjaro i3桌面 怎么设置啊 

### ISSUE THREAD

**Issue by swq1998** [shadowsocksrr/electron-ssr#28]

**Comment by swq1998** [comment]
chrome 配置了代理插件 也用不了

**Comment by xkeyC** [comment]
除gnome外，其他桌面环境看起来都不支持修改系统代理，但你可以打开终端，在飞机图标右键，选择复制http代理设置，之后粘贴进终端，在终端打开需要代理的应用。

**Comment by xkeyC** [comment]
export http_proxy="http://127.0.0.1:12333"
export https_proxy="http://127.0.0.1:12333"

**Comment by xVanTuring** [comment]
如果没有其余问题,就关闭该issues了。
如果有任何问题，可以随时提问。
