### ISSUE TITLE
English support or guide please

### ISSUE THREAD

**Issue by SajadJalilian** [shadowsocksrr/electron-ssr#31]
English support or guide please, 
i can't find any english guide for this UI and i can't figure out how to change language if it exist

**Comment by xVanTuring** [comment]
I will implement this feature, which may take a little bit of time

**Comment by xVanTuring** [comment]
The initial English support(UI part) has been added to branch [0.3.0](https://github.com/xVanTuring/rss-nortcele/tree/v0.3.0) along with other updates, you may want to take a look. 
The menu/tray part will be added after Chinese Spring Festival

**Comment by SajadJalilian** [comment]
thank you very much :)

**Comment by Na0mir** [comment]
That would be awesome ! Thanks !

**Comment by xVanTuring** [comment]
Most part of electron-ssr is now translated, mark it as solved!
