### ISSUE TITLE
[Suggestion]: Remove Shortcut Support

### ISSUE THREAD

**Issue by xVanTuring** [shadowsocksrr/electron-ssr#35]
原作者在添加快捷键时，是考虑到部分Linux系统没有状态栏，而导致程序无法重新打开，最新的[pr](https://github.com/shadowsocksrr/electron-ssr/pull/34)将能够实现重新打开原窗口，因此快捷键功能也变得没有什么意义了。

因此提议将快捷键功能完全删除。

(目前已在我的[fork](https://github.com/xVanTuring/rss-nortcele/tree/remove-shortcut)下进行了)

**Comment by zidoshare** [comment]
复议，快捷键功能已经没有任何意义了

**Comment by a188037445** [comment]
别删，有用啊，我用快捷键来切换pac和全局模式！

**Comment by xVanTuring** [comment]
> 别删，有用啊，我用快捷键来切换pac和全局模式！

原本以为这个功能应该不怎么用的，如果有必要的话可以保留这个功能

**Comment by a188037445** [comment]
> > 别删，有用啊，我用快捷键来切换pac和全局模式！
> 
> 原本以为这个功能应该不怎么用的，如果有必要的话可以保留这个功能

保留吧，如果能提供过滤大陆常见域名的pac，那我就不需要用快捷键了。

**Comment by xVanTuring** [comment]
> 如果能提供过滤大陆常见域名的pac，那我就不需要用快捷键了。

这个功能可以有,破娃酱倒是有个[gfw_whitelist](https://github.com/breakwa11/gfw_whitelist)

**Comment by a188037445** [comment]
> > 如果能提供过滤大陆常见域名的pac，那我就不需要用快捷键了。
> 
> 这个功能可以有,破娃酱倒是有个[gfw_whitelist](https://github.com/breakwa11/gfw_whitelist)

如果能加这个功能就好用多了。
不过我现在在 ubuntu 19.10 上用不了了，依赖都安装了也不行，不知道怎么回事，能否在readme页面告知所需的所有依赖和版本？

**Comment by xVanTuring** [comment]
> 不过我现在在 ubuntu 19.10 上用不了了，依赖都安装了也不行，不知道怎么回事，能否在readme页面告知所需的所有依赖和版本？

你下载的版本还是0.2.7是吧，这个版本的electron太老了已经不准备修补了，新版本的release还没放出来，你可以直接克隆项目自行编译就好了。依赖貌似ubuntu默认都有的，我稍后装个虚拟机测试以下19.10的
如果你要自行编译的话，修改这个文件，去掉你不需要的输出格式，
https://github.com/shadowsocksrr/electron-ssr/blob/42f401f3d83b1a01760a14b4d8c1c22aebb92957/.electron-vue/release.js#L115-L119
然后
``` bash
yarn 
yarn build
```
就行了。
你也可以上传一下具体情况，我可以尝试解决一下：
1. 在终端中执行`electron-ssr`然后上传一下输出
2. 上传 `~/.config/electron-ssr/logs`里的输出

**Comment by a188037445** [comment]
@xVanTuring  编译了半天还是因为网络的问题没打包成功，我把未打包的程序运行了一下，和之前使用 0.2.7 的问题一样，报错和 #25  一样，退出后终端还提示 核心已转储。

**Comment by xVanTuring** [comment]
> @xVanTuring 编译了半天还是因为网络的问题没打包成功，我把未打包的程序运行了一下，和之前使用 0.2.7 的问题一样，报错和 #25 一样，退出后终端还提示 核心已转储。

核心转储不是问题，至于那个[error]正常运行也那样

**Comment by xVanTuring** [comment]
你是通过订阅添加的是吧，有尝试过切换别的服务器节点吗？

**Comment by a188037445** [comment]
> > @xVanTuring 编译了半天还是因为网络的问题没打包成功，我把未打包的程序运行了一下，和之前使用 0.2.7 的问题一样，报错和 #25 一样，退出后终端还提示 核心已转储。
> 
> 核心转储不是问题，至于那个[error]正常运行也那样

但我这就是不能fq，设置和节点都已确认过了，没问题，我用同样的节点在手机上都能用。也换了几个节点试过了，都不行。

**Comment by xVanTuring** [comment]
2020-01-13 08:23:45:335 [info] run command: python /home/user/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s __www.google.com__ -p 1 -k ****** -m chacha20 -O auth_chain_a -o tls1.2_ticket_auth -b 0.0.0.0 -l 1080

你这使用的是google作为服务器阿

**Comment by a188037445** [comment]
> 2020-01-13 08:23:45:335 [info] run command: python /home/user/.config/electron-ssr/shadowsocksr/shadowsocks/local.py -s **www.google.com** -p 1 -k ****** -m chacha20 -O auth_chain_a -o tls1.2_ticket_auth -b 0.0.0.0 -l 1080
> 
> 你这使用的是google作为服务器阿

这是因为我退出后节点设置不能保存，所以每次重新打开节点就变成第一个了（第一个节点只是一个说明，不是真的节点），打开后手动切换节点也不能用。

**Comment by xVanTuring** [comment]
双击节点才能切换，然后才保存的

**Comment by a188037445** [comment]
> 双击节点才能切换，然后才保存的

怎么是这样的。。。。
我之前单击的节点，然后看到节点也选中了啊。。
现在好了，双击就可以了。

**Comment by xVanTuring** [comment]
> > 双击节点才能切换，然后才保存的
> 
> 怎么是这样的。。。。
> 我之前单击的节点，然后看到节点也选中了啊。。
> 现在好了，双击就可以了。

反正都是原作者的锅

**Comment by a188037445** [comment]
> 
> 反正都是原作者的锅

可把我坑惨了，为了这个东西耽误了几天的时间。。

**Comment by xVanTuring** [comment]
> > 反正都是原作者的锅
> 
> 可把我坑惨了，为了这个东西耽误了几天的时间。。

计划更新一波UI，更直观一些

**Comment by xVanTuring** [comment]
https://github.com/shadowsocksrr/electron-ssr/pull/48
App-Menu toggle is now removd, the global shortcut is kept.
