### ISSUE TITLE
[提议]:优化主界面功能排版设计

### ISSUE THREAD

**Issue by zidoshare** [shadowsocksrr/electron-ssr#38]
主窗口中，设置界面：
![image](https://user-images.githubusercontent.com/11310504/72235826-37650c80-360f-11ea-9778-a6386e3cef1c.png)
与服务器选择界面：
![image](https://user-images.githubusercontent.com/11310504/72235931-c3773400-360f-11ea-8aca-d2a933f2533c.png)
无法很好的切换。

提议直接将主界面和设置界面整合到一起，不再割裂开

**Comment by xVanTuring** [comment]
这个问题我也注意到了，临时可以通过添加一个menu来解决

**Comment by zidoshare** [comment]
我建议将服务器选择作为主界面，然后将设置放到menu中，目前我有两个提案

### 1：通过点击 [配置]->[应用设置]切换到设置界面
### 2：把四个tab标签也展开到
像这样的结构:
|--配置
|------通用设置
|------SSR设置
|------订阅管理
|------快捷键管理
|------打开配置文件
|------等等...

**Comment by xVanTuring** [comment]
这是刚刚做好的主页面的一个重置，优化了检视节点和使用节点的区别，然后把二维码通过一个checkbox隐藏起来。
节点列表使用的是自定义的简化后的树，移除了对分组的移动操作，后面也许可以可以添加鼠标右键移动分组。
![prev](https://user-images.githubusercontent.com/11146248/72579732-98a30f00-389f-11ea-8556-f7c2ebcfd550.png)

**Comment by xVanTuring** [comment]
https://github.com/shadowsocksrr/electron-ssr/pull/48
