### ISSUE TITLE
linux CMD命令行下能用electron-ssr吗

### ISSUE THREAD

**Issue by mebest100** [shadowsocksrr/electron-ssr#42]
OS:CentOS7.6(最小化安装，没有GUI X环境)
linux CMD命令行下能用electron-ssr吗

**Comment by Dimerbone** [comment]
首先，linux终端根本不叫cmd，其次，命令行用你还不如用shadowsocksR-libv



---原始邮件---
发件人: "mebest100"<notifications@github.com&gt;
发送时间: 2020年1月28日(周二) 晚上8:24
收件人: "shadowsocksrr/electron-ssr"<electron-ssr@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [shadowsocksrr/electron-ssr] linux CMD命令行下能用electron-ssr吗 (#42)



OS:CentOS7.6
 linux CMD命令行下能用electron-ssr吗

**Comment by mebest100** [comment]
大哥，我是linux 管理员，难道我不知道什么什么是终端吗，CMD只是一种简单的说法。
关键是shadowsocksR-libv不能支持obfs等混淆参数啊

**Comment by mebest100** [comment]
自己解决了

**Comment by chenerg** [comment]
> 自己解决了

能不能问一下你怎么解决的

**Comment by huangatlas** [comment]
@mebest100 是怎么解决的呀
