### ISSUE TITLE
cannot start at login on Manjaro

### ISSUE THREAD

**Issue by heyizhang** [shadowsocksrr/electron-ssr#46]
## Your os
Linux(Manjaro kde)

## The version of electron-ssr
v0.2.7

## What's the problem
I configured it to start at login  in electron-ssr setting, but when  i start Manjaro,  electron default app just pop out, and say:

To run a local app, execute the following on the command line:

/usr/lib/electron4/electron path-to-app

![image](https://user-images.githubusercontent.com/33022132/73903462-25a41b80-48d4-11ea-9e99-6d33576f74d2.png)

**Comment by xVanTuring** [comment]
This might be a pacman package problem, the archlinux-cn package it with electron-4 which should be electron-2.
This should be fixed after v0.3.0 released

**Comment by vio1etus** [comment]
Yes, I tried to install v0.2.7 release manually，It turns out it's works fine. Thank you very much！
