### ISSUE TITLE
pacman包未包含对gconf的依赖

### ISSUE THREAD

**Issue by xkeyC** [shadowsocksrr/electron-ssr#49]
Archlinux在使用时，直接安装pacman包后无法直接使用，终端输出是未找到llibgconf-2.so.4，通过手动安装gconf包解决问题。建议下次打包时包含此依赖。

**Comment by CECoffee** [comment]
manjaro有同样问题



---原始邮件---
发件人: "xkeyC"<notifications@github.com&gt;
发送时间: 2020年2月10日(周一) 中午11:51
收件人: "shadowsocksrr/electron-ssr"<electron-ssr@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [shadowsocksrr/electron-ssr] pacman包未包含对gconf的依赖 (#49)



Archlinux在使用时，直接安装pacman包后无法直接使用，终端输出是未找到llibgconf-2.so.4，通过手动安装gconf包解决问题。建议下次打包时包含此依赖。

**Comment by xVanTuring** [comment]
Thanks for your suggestion!
