### ISSUE TITLE
Linux系统下，建议支持ss连接，其他客户端功能用的太不好了，只有这个electron-ssr客户端比较好

### ISSUE THREAD

**Issue by ghost** [shadowsocksrr/electron-ssr#52]

**Comment by xVanTuring** [comment]
We will take a look at it! Thanks for your advice!

**Comment by xVanTuring** [comment]
Currently, the SSR is unmaintained, so the support of electron-ssr will not last very long.
I will try to create a lite version based on server/web/chrome instead of Electron.
