### ISSUE TITLE
Suggestion: Do not open the software main interface when open the software(for ver 0.3.0)

### ISSUE THREAD

**Issue by vocaloidchina** [shadowsocksrr/electron-ssr#63]
Many people do not need to open the main application interface each time when using the application, they may only need to run in the background.

**Comment by xVanTuring** [comment]
It used to work like that, but in Linux/Gnome Env there is no `tray` now, so user will need the menu in the main window.
I guess an option for that will be enough. How about that?

**Comment by vocaloidchina** [comment]
@xVanTuring This idea looks great!

**Comment by xVanTuring** [comment]
Added at: https://github.com/shadowsocksrr/electron-ssr/pull/70
