### ISSUE TITLE
[Macos] Not found Copy Http Settings Item

### ISSUE THREAD

**Issue by xkeyC** [shadowsocksrr/electron-ssr#67]
## Your os
macOS 10.15.3

## The version of electron-ssr
0.3.0-alpha.3

## What's the problem
Updated to 0.3.0,the IconMenu not found copy Http Settings item，So I can't use proxy in terminal.
![image](https://user-images.githubusercontent.com/39891083/75646714-7dd8fe00-5c85-11ea-9a9b-0669751f670e.png)

**Comment by xVanTuring** [comment]
Well, You can type `export http_proxy=http://127.0.0.1:HTTP_PORT` and  `export https_proxy=http://127.0.0.1:HTTP_PORT`. I will fix it soon

**Comment by xVanTuring** [comment]
Fixed at: https://github.com/shadowsocksrr/electron-ssr/pull/70
