### ISSUE TITLE
System Proxy Mode: Global not working.

### ISSUE THREAD

**Issue by circlecrystal** [shadowsocksrr/electron-ssr#68]
## Your os

Ubuntu 19.10
## The version of electron-ssr

v0.3.0-alpha.3
## What's the problem

System proxy mode PAC Proxy works correctly, however the Global mode doesn't allow any proxy service at all. Any connection is lost in Global mode.

**Comment by xVanTuring** [comment]
Could you give me a screenshot of you gnome setting of network proxy?

**Comment by xVanTuring** [comment]
Good news! I get the same problem now, fixing!

**Comment by xVanTuring** [comment]
@circlecrystal Can you tell me what browser you are using? After testing on chromium with global proxy the problem disappears, but it does occur in Firefox

**Comment by circlecrystal** [comment]
I'm using Firefox. Thanks!

**Comment by xVanTuring** [comment]
You might want use SwitchyOmega to enable global proxy in Firefox, or set manually in `Network Settings`, option `Proxy DNS when using SOCKS v5` need to be turned on.

Feel free to ask any question.
