### ISSUE TITLE
开机自启后会自动打开窗口

### ISSUE THREAD

**Issue by ghost** [shadowsocksrr/electron-ssr#69]
我的系统是 Debian testing，electron-ssr 版本是 0.3.0-alpha.3，勾选开机自启后，每次开机都会自动弹出窗口（就是主界面窗口），之前用的 0.2.7 版本不会。

而且新版还有个小问题，每次使用快捷键打开窗口时有点延迟，大概有 1 秒左右才会显示出来（KDE桌面）。

**Comment by GoldJohnKing** [comment]
Ubuntu 18.04.4 with Gnome has the same issue.

**Comment by xVanTuring** [comment]
Fixed at: https://github.com/shadowsocksrr/electron-ssr/pull/70
