### ISSUE TITLE
manjaro无法显示系统图标

### ISSUE THREAD

**Issue by Elliott12138** [shadowsocksrr/electron-ssr#7]
manjaro无法显示系统图标

**Comment by Akkariiin** [comment]
主要功能能用吗？能用就行

**Comment by VariousTrick** [comment]
chromeos上不装linux桌面隐藏掉也打不开界面了，很麻烦。。

**Comment by defaultwalter** [comment]
好像是electron的问题

> On Linux distributions that only have app indicator support, you have to install libappindicator1 to make the tray icon work.

同为manjaro使用gnome桌面。 安装 libappindicator-gtk3 后就可以显示了。

参考：[https://electronjs.org/docs/api/tray](https://electronjs.org/docs/api/tray)

**Comment by puzzle9** [comment]
https://github.com/phocean/TopIcons-plus
如果是 gnome 试试这个扩展
