### ISSUE TITLE
导出配置到文件报错

### ISSUE THREAD

**Issue by commis** [shadowsocksrr/electron-ssr#72]
操作系统：Linux Mint 19
electron-ssr版本：v0.3.0-alpha.4

从任务栏图表上弹出的菜单 设置->导出GUI config.json文件 直接报错。
![image](https://user-images.githubusercontent.com/6156769/76513329-1bf07380-6491-11ea-8092-79a7ad86bbdb.png)

**Comment by xVanTuring** [comment]
I'll fix it ASAP.

**Comment by xVanTuring** [comment]
fixed: https://github.com/shadowsocksrr/electron-ssr/pull/74 
Free feel to reopen it if anything goes wrong
