### ISSUE TITLE
启动时显示找不到python文件

### ISSUE THREAD

**Issue by fhzyfjy** [shadowsocksrr/electron-ssr#8]
启动时显示找不到python文件（已安装python)
![image](https://user-images.githubusercontent.com/11030827/61966186-9bb1f680-b004-11e9-8301-c165e954a828.png)

**Comment by Akkariiin** [comment]
把py加入环境变量即可

**Comment by fhzyfjy** [comment]
具体如何加啊？我是小白。要是能把这个SSR软件做成免安装解压版的就好了。

**Comment by fhzyfjy** [comment]
网上搜了一下，安装方法会了。PY是安装2的还是3的？

**Comment by fhzyfjy** [comment]
TG地址？

**Comment by fhzyfjy** [comment]
mac\windows系统都无法使用。mac更新订阅节点显示“可更新节点是零”。使用ShadowsocksX-NG-R没问题
