### ISSUE TITLE
在系统托盘找不到图标

### ISSUE THREAD

**Issue by HaoliangXu** [shadowsocksrr/electron-ssr#83]
## Your os

Arch Linux
## The version of electron-ssr

0.3.0 Alpha-5
## What's the problem

在系统托盘找不到图标。无论主窗口是打开还是关闭，都没有图标。

**Comment by xVanTuring** [comment]
这个是gnome的锅，它把tray给删除了，你需要用第三方插件，主页的readme里面有提到

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________
