### ISSUE TITLE
Ubuntu 20.04 提示找不到 python (No python detected)

### ISSUE THREAD

**Issue by Provissy** [shadowsocksrr/electron-ssr#86]
Ubuntu 20.04 Focal 默认自带python3.8， 但是根据指引， 所有引用python的包必须显示指定`python3`或其他python版本。

Ubuntu从20.04开始不再将`python`加入`$PATH`，而Electron-SSR默认调用`python`而不是`python3`。这导致Electron-SSR无法运行并提示找不到python，然而python3与python2都已安装。

解决方法：
`sudo apt install python-is-python3`

或者手动创建symlink
`sudo ln -s /usr/bin/python3 /usr/bin/python`

检视是否成功：
`$ whereis python`

**Comment by ghost** [comment]
万众期待的正式版呢

**Comment by lightis-tian** [comment]
> Ubuntu 20.04 Focal 默认自带python3.8， 但是根据指引， 所有引用python的包必须显示指定`python3`或其他python版本。
> 
> Ubuntu从20.04开始不再将`python`加入`$PATH`，而Electron-SSR默认调用`python`而不是`python3`。这导致Electron-SSR无法运行并提示找不到python，然而python3与python2都已安装。
> 
> 解决方法：
> `sudo apt install python-is-python3`
> 
> 或者手动创建symlink
> `sudo ln -s /usr/bin/python3 /usr/bin/python`
> 
> 检视是否成功：
> `$ whereis python`

yes, thank you very much!

**Comment by xVanTuring** [comment]
fixed

**Comment by cyfex** [comment]
This is not fixed in the source code. The post just shows a workaround. But the repository contributors should update their code to fix this issue.
