### ISSUE TITLE
Does it support user-rules for pac?

### ISSUE THREAD

**Issue by taraxacum45e9a** [shadowsocksrr/electron-ssr#87]
## Your os

Ubuntu 18.04.4 LTS \n \l
5.3.0-51-generic

## The version of electron-ssr

electron-ssr v0.27

## What's the problem

FEATURE REQUEST

Support user-rules for pac

**Comment by jizongFox** [comment]
any answer to this ?

**Comment by taraxacum45e9a** [comment]
> any answer to this ?

Not at all

You may turn to some v2ray client, which usually supports shadowsocks as well.
