### ISSUE TITLE
Manjaro kde without libappindicator-sharp

### ISSUE THREAD

**Issue by Imtinmin** [shadowsocksrr/electron-ssr#88]
## Your os
```
Linux(Manjaro kde)
```

## The version of electron-ssr
v0.2.7

## What's the problem

`yay -U electron-ssr.pacman`have error
```
without "libappindicator-sharp"
```

![img](https://user-images.githubusercontent.com/38977612/83225503-82dd1900-a1b2-11ea-8849-376b0cb06ff9.png)

**Comment by xVanTuring** [comment]
please try version 0.3.0-alpha, the 0.2.7 is no longer supported

**Comment by Imtinmin** [comment]
> please try version 0.3.0-alpha, the 0.2.7 is no longer supported

ok ,solved.Thanks

**Comment by vfdxvffd** [comment]
> > 请尝试版本0.3.0-alpha，不再支持0.2.7
> 
> 好的，解决了。谢谢

请问您是怎么解决的这个问题，0.3.0-alpha在哪下载呢？

**Comment by Imtinmin** [comment]
> > > 请尝试版本0.3.0-alpha，不再支持0.2.7
> > 
> > 
> > 好的，解决了。谢谢
> 
> 请问您是怎么解决的这个问题，0.3.0-alpha在哪下载呢？

https://github.com/shadowsocksrr/electron-ssr/releases/

**Comment by vfdxvffd** [comment]
> > > > 请尝试版本0.3.0-alpha，不再支持0.2.7
> > > 
> > > 
> > > 好的，解决了。谢谢
> > 
> > 
> > 请问您是怎么​​解决的这个问题，0.3.0-alpha在哪下载呢？
> 
> https://github.com/shadowsocksrr/electron-ssr/releases/

感谢您的回复，解决了，多谢
